# Generated by Django 2.0.1 on 2018-01-15 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160801_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='BicubicImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='bicubic/')),
            ],
        ),
        migrations.CreateModel(
            name='SrcnnImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='srcnn/')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='srcnnimage',
            name='original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Document'),
        ),
        migrations.AddField(
            model_name='bicubicimage',
            name='original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Document'),
        ),
    ]
